name: "Configure and build"
description: "Generate the build files and build the code"
runs:
  using: "composite"
  steps:

    - name: Prepare compiler env
      shell: sh
      run: |
        echo "CC=${{ matrix.config.cc }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.config.cxx }}" >> $GITHUB_ENV

    - name: configure
      shell: sh
      run: |
        mkdir $CILOGG_BUILD_ROOT
        cd $CILOGG_BUILD_ROOT
        EXTRA_CMAKE_OPTS=""
        if [ -n "$QT_TOOLCHAIN_FILE" ]; then
          EXTRA_CMAKE_OPTS="$EXTRA_CMAKE_OPTS -DCMAKE_TOOLCHAIN_FILE=$QT_TOOLCHAIN_FILE"
        fi
        cmake $CILOGG_CMAKE_OPTS $EXTRA_CMAKE_OPTS -DCPM_SOURCE_CACHE=$CILOGG_WORKSPACE/cpm_cache -DKLOGG_OVERRIDE_MALLOC=OFF $CILOGG_WORKSPACE

    - name: build
      shell: sh
      run: |
        cmake --build $CILOGG_BUILD_ROOT -t ci_build
