name: "Run tests in container"
description: "Run all the tests in container"
runs:
  using: "composite"
  steps:
    - name: test
      shell: sh
      run: |
        docker run $CILOGG_DOCKER_PLATFORM --env CILOGG_BUILD_ROOT=$CILOGG_BUILD_ROOT -v "$CILOGG_WORKSPACE":/usr/local ${{ matrix.config.container }} /bin/bash -c "cd /usr/local/$CILOGG_BUILD_ROOT && ctest --verbose"

