name: "Build and test in container"
description: "Generate the build files, build the code and run the tests"
runs:
  using: "composite"
  steps:
    - name: configure
      shell: sh
      run: |
        docker run $CILOGG_DOCKER_PLATFORM --env CILOGG_VERSION=$CILOGG_VERSION --env CILOGG_BUILD_ROOT=$CILOGG_BUILD_ROOT --env CILOGG_CMAKE_OPTS="$CILOGG_CMAKE_OPTS" -v "$CILOGG_WORKSPACE":/usr/local ${{ matrix.config.container }} /bin/bash -c "cmake -B /usr/local/$CILOGG_BUILD_ROOT $CILOGG_CMAKE_OPTS -DCPM_SOURCE_CACHE=/usr/local/cpm_cache /usr/local"

    - name: build
      shell: sh
      run: |
        docker run $CILOGG_DOCKER_PLATFORM --env CILOGG_BUILD_ROOT=$CILOGG_BUILD_ROOT -v "$CILOGG_WORKSPACE":/usr/local ${{ matrix.config.container }} /bin/bash -c "cmake --build /usr/local/$CILOGG_BUILD_ROOT --target ci_build"
